version: 2

models:
  - name: reporting__customer_promo_response_base
    description: >
      Customer-level reporting base that calculates the promotion response rate.
      Useful for segmentation by demographic profile and promotional behavior analysis.
    columns:
      - name: customer_id
        description: Unique identifier of the customer.
        tests:
          - not_null
          - unique
      - name: income
        description: Income bracket assigned to the customer.
        tests:
          - not_null
      - name: age
        description: Age of the customer.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 10
              max_value: 150
      - name: gender
        description: Customer gender.
        tests:
          - not_null
          - accepted_values:
              values: ['M', 'F', 'O']
      - name: promo_trans_count
        description: Number of transactions with promotion made by the customer.
        tests:
          - not_null
      - name: total_trans_count
        description: Total transactions (with and without promotion) made by the customer.
        tests:
          - not_null
      - name: pct_promo_response
        description: Percentage of transactions with promotion (promo_trans_count / total_trans_count).
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 1.0
