version: 1

models:
  - name: rep_customer_responsiveness
    config:
      contract:
        enforced: true
    description: |
      Reporting model that analyzes customer responsiveness to promotional offers based on demographic and behavioral segments.
      Each row aggregates customer actions by gender, age, income, and segmentations such as promo behavior, age group, income group, and customer's subscription years group.
      Includes counts of promotion events and the view rate.
      This model does not analyze individual promotion attributes, focusing instead on customer segments and their response metrics.
    columns:
      - name: gender
        description: Gender of the customer.
        data_type: string
        data_tests:
          - not_null
          - accepted_values:
              values:
                - M
                - F
                - O
                - N/A
      - name: age
        description: Age of the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: age_group
        description: Age group assigned to the customer according to the age_group macro.
        data_type: string
        data_tests:
          - not_null
      - name: income
        description: Income of the customer.
        data_type: float64
        data_tests:
          - not_null
      - name: income_group
        description: Income group assigned to the customer according to the income_group macro.
        data_type: string
        data_tests:
          - not_null
      - name: customer_subscribed_date
        description: Date when the customer created an app account.
        data_type: date
        data_tests:
          - not_null
      - name: customer_subscription_years_group
        description: Customer's subscription years group, as defined by the `subscription_years_group` macro.
        data_type: string
        data_tests:
          - not_null
      - name: subscribed_year
        description: Year part extracted from the subscription date.
        data_type: integer
        data_tests:
          - not_null
      - name: subscribed_month
        description: Month part extracted from the subscription date (1-12).
        data_type: integer
        data_tests:
          - not_null
      - name: subscribed_day
        description: Day of month extracted from the subscription date (1-31).
        data_type: integer
        data_tests:
          - not_null
      - name: subscribed_dayofweek
        description: Day of week extracted from the subscription date (1=Sunday, 7=Saturday in BigQuery).
        data_type: integer
        data_tests:
          - not_null
      - name: promos_received
        description: Number of promotions received by the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: promos_viewed
        description: Number of promotions viewed by the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: promos_completed
        description: Number of promotions completed by the customer.
        data_type: integer
        data_tests:
          - not_null
      - name: promos_transaction
        description: Number of promotions where the customer performed a 'transaction'.
        data_type: integer
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
      - name: promo_behavior_segment
        description: |
          Segment assigned to the customer according to their promotional behavior:
          - 'No-promo-only': Only transactions without promotion
          - 'Promo-only': Only transactions with promotion
          - 'Mixed': Both transactions with and without promotion
          - 'Undefined': No data or could not be classified
        data_type: string
        data_tests:
          - not_null
          - accepted_values:
              values:
                - No-promo-only
                - Promo-only
                - Mixed
                - Undefined
      - name: view_rate
        description: |
          Percentage of received promotions that were viewed by the customer.
          Calculated with the `response_rate` macro: viewed / received (0 if received is 0).
        data_type: float64
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
  - name: rep_channel_effectiveness
    config:
      contract:
        enforced: true
    description: |
      Reporting model that analyzes the effectiveness of each communication channel and promotion type in driving customer responses to offers.
      Each row aggregates the number of promotions received and viewed, and calculates the view rate (in percentage, 0–100), by channel, promotion type, difficulty, reward, duration, and elapsed time since offer start.
      This model enables business users to compare which channels and types are more effective at engaging customers, as well as trends based on offer characteristics and timing.
    columns:
      - name: promo_channel
        description: Communication channel through which the offer was delivered (email, mobile, social, web).
        data_type: string
        data_tests:
          - not_null
          - accepted_values:
              values:
                - email
                - mobile
                - social
                - web
      - name: promo_type
        description: Type of promotion (bogo, discount, informational).
        data_type: string
        data_tests:
          - not_null
          - accepted_values:
              values:
                - bogo
                - discount
                - informational
      - name: promo_difficulty_rank
        description: Minimum spending required to complete the offer.
        data_type: integer
        data_tests:
          - not_null
      - name: promo_reward
        description: Reward given upon completion of the offer.
        data_type: integer
        data_tests:
          - not_null
      - name: promos_received
        description: Number of times the promotion was received in this group.
        data_type: integer
        data_tests:
          - not_null
      - name: promos_viewed
        description: Number of times the promotion was viewed in this group.
        data_type: integer
        data_tests:
          - not_null
      - name: view_rate
        description: |
          Percentage of received promotions that were viewed (promos_viewed / promos_received, or 0 if promos_received = 0).
          Calculated using the `response_rate` macro.
        data_type: float64
        data_tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0
              max_value: 100
      - name: promo_duration
        description: Time in minutes for the offer to be open.
        data_type: integer
        data_tests:
          - not_null
      - name: hours_since_start
        description: Time in hours since the offer was received.
        data_type: integer
        data_tests:
          - not_null
      - name: days_since_start
        description: Time in days since the offer was received.
        data_type: integer
        data_tests:
          - not_null
      - name: ingested_at
        description: Timestamp when the data was ingested.
        data_type: timestamp
        data_tests:
          - not_null
