version: 2

models:
  - name: reporting__customer_promo_response_base
    description: >
      Base de reporting a nível de cliente que calcula a taxa de resposta a promoções.
      Útil para segmentações por perfil demográfico e análise de comportamento promocional.
    columns:
      - name: customer_id
        description: Identificador único do cliente.
        tests:
          - not_null
          - unique
      - name: income
        description: Faixa de rendimento atribuída ao cliente.
        tests:
          - not_null
      - name: age
        description: Idade do cliente.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 10
              max_value: 150
      - name: gender
        description: Gênero do cliente.
        tests:
          - not_null
          - accepted_values:
              values: ['M', 'F', 'O']
      - name: promo_trans_count
        description: Número de transações com promoção realizadas pelo cliente.
        tests:
          - not_null
      - name: total_trans_count
        description: Total de transações (com e sem promoção) feitas pelo cliente.
        tests:
          - not_null
      - name: pct_promo_response
        description: Percentual de transações com promoção (promo_trans_count / total_trans_count).
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 1.0
