version: 2

models:
  - name: reporting__customer_promo_response_base
    description: >
      Customer-level reporting base that calculates the promotion response rate.
      Useful for segmentation by demographic profile and promotional behavior analysis.
    columns:
      - name: customer_id
        description: Unique identifier of the customer.
        tests:
          - not_null
          - unique
      - name: income
        description: Income bracket assigned to the customer.
        tests:
          - not_null
      - name: age
        description: Age of the customer.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 10
              max_value: 150
      - name: gender
        description: Customer gender.
        tests:
          - not_null
          - accepted_values:
              values: ['M', 'F', 'O']
      - name: promo_trans_count
        description: Number of transactions with promotion made by the customer.
        tests:
          - not_null
      - name: total_trans_count
        description: Total transactions (with and without promotion) made by the customer.
        tests:
          - not_null
      - name: pct_promo_response
        description: Percentage of transactions with promotion (promo_trans_count / total_trans_count).
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 1.0

  - name: reporting_customer_promo_response_summary
    description: >
      Aggregated metrics of promotion response by demographic group (income, gender, age).
      Enables analysis of promotional behavior patterns across customer segments.
    columns:
      - name: income
        description: Income bracket assigned to the customer.
        tests:
          - not_null
      - name: gender
        description: Gender of the customer.
        tests:
          - not_null
          - accepted_values:
              values: ['M', 'F', 'O']
      - name: age
        description: Age of the customer.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 10
              max_value: 150
      - name: total_customers
        description: Total number of customers in the demographic group.
        tests:
          - not_null
      - name: responded_customers
        description: Number of customers who responded to at least one promotion.
        tests:
          - not_null
      - name: avg_response_rate
        description: Average response rate to promotions within the group.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 1.0
      - name: pct_customers_responded
        description: Percentage of customers who responded to at least one promotion in the group.
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_between:
              min_value: 0.0
              max_value: 1.0

  - name: promo_channel_effectiveness
    description: >
      Aggregates marketing promotion performance metrics by communication channel
      and promotion type. Helps assess the effectiveness of email, mobile, social,
      and web channels in engaging customers with different types of promotions.

    columns:
      - name: channel
        description: Channel through which the promotion was delivered (e.g., email, mobile, social, web).
        tests:
          - not_null
          - accepted_values:
              values: ['email', 'mobile', 'social', 'web']

      - name: promo_type
        description: Type of promotion offered to the customer (e.g., bogo, discount, informational).
        tests:
          - not_null
          - accepted_values:
              values: ['bogo', 'discount', 'informational']

      - name: customers_responded
        description: Number of unique customers who responded to a promotion in the given channel and promo type.
        tests:
          - not_null

      - name: total_promos
        description: Number of unique promotions delivered in the given channel and promo type.
        tests:
          - not_null

      - name: avg_difficulty_rank
        description: Average difficulty rank (effort needed to complete promotion) for that channel and promo type.
        tests:
          - not_null

      - name: avg_reward
        description: Average reward (in monetary or point value) offered in that channel and promo type.
        tests:
          - not_null
