services:
  dbt:
    build: .
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /root/secrets/application_default_credentials.json
      PROJECT_ID: ${GCP_PROJECT_ID}
    volumes:
      - ${GCLOUD_CREDENTIALS_FILEPATH}:/root/secrets/application_default_credentials.json
      - ./:/opt/dbt/
    ports:
      - "8080:8080"
