services:
  dbt:
    build: .
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${KEYFILE_PATH}
      - PROJECT_ID=${GCP_PROJECT_ID}
    volumes:
      - ${KEYFILE_PATH}:/root/secrets/service_account.json
