name: "starbucks_dw"
version: "1.0.0"
profile: "starbucks_dw"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

vars:
  schema_prefix: "daniel"

models:
  starbucks_dw:
    staging:
      +materialized: view
    marts:
      +materialized: table
