starbucks_dw:
  target: dev
  outputs:
    dev:
      dataset: starbucks_dev
      location: EU
      method: oauth
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 4
      type: bigquery

    prod:
      dataset: starbucks_prod
      keyfile: "{{ env_var('GOOGLE_APPLICATION_CREDENTIALS') }}"
      location: EU
      method: service-account
      project: "{{ env_var('PROJECT_ID') }}"
      threads: 4
      type: bigquery
