starbucks_dw:
  target: dev
  outputs:
    dev:
      dataset: starbucks_dev
      keyfile: '{{ env_var(''EDIT_GOOGLE_APPLICATION_CREDENTIALS'') }}'
      location: EU
      method: service-account
      project: '{{ env_var(''EDIT_PROJECT_ID'') }}'
      threads: 4
      type: bigquery

    prod:
      dataset: starbucks_prod
      keyfile: '{{ env_var(''EDIT_GOOGLE_APPLICATION_CREDENTIALS'') }}'
      location: EU
      method: service-account
      project: '{{ env_var(''EDIT_PROJECT_ID'') }}'
      threads: 4
      type: bigquery
