version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer

  - name: format_transaction_type
    description: Treatment of transaction status
    arguments:
      - name: transaction_type
        description: The type of transaction
        type: string
