version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer
  - name: format_transaction_status
    description: |
      Maps transaction type strings to status labels:
        - 'offer received' -> 'received'
        - 'offer viewed' -> 'viewed'
        - 'offer completed' -> 'completed'
        - 'transaction' -> 'transaction'
        - any other -> 'unknown'
    arguments:
      - name: transaction_type_column
        description: The column containing the transaction type string
