version: 2

macros:
  - name: get_days_from_hours
    description: Convert hours to days.
    arguments:
      - name: hours
        description: Number of hours.
        type: integer
  - name: format_transaction_type
    description: Format the transaction type to a more readable format.
    arguments:
      - name: transaction_type
        description: The column containing the transaction type.
        type: string
