version: 2

sources:
  - name: starbucks
    database: "{{ target.database }}"
    schema: starbucks_raw
    tables:
      - name: promos
        description: Information about the promotional offers that are possible to receive, and basic information about each one.
        columns:
          - name: reward
            description: Reward given for completing an offer.
          - name: channels
            description: A list of channels through which the offer was received.
          - name: difficulty
            description: Minimum required spend to complete the offer.
          - name: duration
            description: Time in minutes for the offer to be open.
          - name: offer_type
            description: Type of offer.
          - name: id
            description: Unique identifier for each offer.
      - name: transactions
        description: Information about the different steps of promotional offers that a customer receives. It also contains information about the transactions that the customer makes.
        columns:
          - name: person
            description: Unique identifier for each customer.
          - name: event
            description: Type of event. Can be offer received, offer viewed, transaction, or offer completed.
          - name: value
            description: Value/identifier of the event.
          - name: time
            description: Time in hours since the start of the test.
      - name: customers
        description: Information about the customers that are part of the promotional offers program.
        columns:
          - name: gender
            description: Gender of the customer.
          - name: age
            description: Age of the customer.
          - name: id
            description: Unique identifier for each customer.
          - name: become_member_on
            description: Date when the customer created an app account.
          - name: income
            description: Income of the customer.
