name: Build and Deploy data models

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  EDIT_PROJECT_ID: ${{ vars.EDIT_PROJECT_ID }}
  EDIT_KEYFILE_GCP: ${{ secrets.EDIT_KEYFILE_GCP }}
  DBT_PROFILES_DIR: ./starbucks_dw
  DBT_PROJECT_DIR: ./starbucks_dw
  DBT_TARGET_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint Python scripts
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    # - name: Lint dbt project scripts
    #   uses: pre-commit/action@v3.0.1
    - name: Check database connection
      run: dbt debug
    - name: Install dbt packages
      run: dbt deps
    - name: Run and test dbt models
      run: dbt build --target $DBT_TARGET_ENV
